package com.lewis.base.entity;

import java.io.Serializable;

public class User implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.account
     *
     * @mbg.generated
     */
    private String account;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.zhuanye
     *
     * @mbg.generated
     */
    private String zhuanye;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.img
     *
     * @mbg.generated
     */
    private String img;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.banji
     *
     * @mbg.generated
     */
    private String banji;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.faceid
     *
     * @mbg.generated
     */
    private String faceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id
     *
     * @return the value of user.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id
     *
     * @param id the value for user.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.account
     *
     * @return the value of user.account
     *
     * @mbg.generated
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.account
     *
     * @param account the value for user.account
     *
     * @mbg.generated
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.zhuanye
     *
     * @return the value of user.zhuanye
     *
     * @mbg.generated
     */
    public String getZhuanye() {
        return zhuanye;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.zhuanye
     *
     * @param zhuanye the value for user.zhuanye
     *
     * @mbg.generated
     */
    public void setZhuanye(String zhuanye) {
        this.zhuanye = zhuanye == null ? null : zhuanye.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.name
     *
     * @return the value of user.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.name
     *
     * @param name the value for user.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.img
     *
     * @return the value of user.img
     *
     * @mbg.generated
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.img
     *
     * @param img the value for user.img
     *
     * @mbg.generated
     */
    public void setImg(String img) {
        this.img = img == null ? null : img.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.banji
     *
     * @return the value of user.banji
     *
     * @mbg.generated
     */
    public String getBanji() {
        return banji;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.banji
     *
     * @param banji the value for user.banji
     *
     * @mbg.generated
     */
    public void setBanji(String banji) {
        this.banji = banji == null ? null : banji.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.faceid
     *
     * @return the value of user.faceid
     *
     * @mbg.generated
     */
    public String getFaceid() {
        return faceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.faceid
     *
     * @param faceid the value for user.faceid
     *
     * @mbg.generated
     */
    public void setFaceid(String faceid) {
        this.faceid = faceid == null ? null : faceid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", account=").append(account);
        sb.append(", zhuanye=").append(zhuanye);
        sb.append(", name=").append(name);
        sb.append(", img=").append(img);
        sb.append(", banji=").append(banji);
        sb.append(", faceid=").append(faceid);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}